services:

  jupyterlab:

    image: tides

    env_file:

      - .env

    ports:

      - "8888:8888"
      - "8050:8050"

    volumes:

      - ./:/Tides

    networks:

      - tidesnetwork


  postgres:

    image: postgis/postgis:15-3.4
    platform: linux/amd64

    env_file:

      - .env

    ports:

      - "5432:5432"

    volumes:

      - postgresdata:/var/lib/postgresql/data

    networks:

      - tidesnetwork
  
  mongo: 
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks: 
      - tidesnetwork

 

volumes:
  postgresdata:
  mongodata:

 

networks:
  tidesnetwork:
